---
# handlers file for emarins.ocp

 - name: Restart DNS service
   service:
     name: named
     state: restarted

 - name: Restart haproxy service
   service:
     name: haproxy
     state: restarted

 - name: Restart vsftpd service
   service:
     name: vsftpd
     state: restarted
